[package]
name = "codelist-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "codelist"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.3", features = ["extension-module"] }
#codelist-rs = { path = "../rust/codelist-rs" }
